---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta12
kind: Kustomization
metadata:
  name: fsa-installation
  namespace: argocd
spec:
  prune: true
  interval: 2m
  path: "./clusters/pun-cluster/sub-system/fsa-installation/kustomization.yaml"
  sourceRef:
    kind: GitRepository
    name: pun-fsa
    namespace: flux-system
  timeout: 10m
  targetNamespace: argocd
  wait: true
