apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-app
spec:
  ports:
  - port: 8001
    nodePort: 30000
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
