apiVersion: apps/v1
kind: Deployment
metadata:
  name: pun-api
  namespace: pun-namespace
spec:
  selector:
    matchLabels:
      app: pun-api
  replicas: 3
  template:
    metadata:
      labels:
        app: pun-api
    spec:
      containers:
      - name: pun-api
        image: ghcr.io/aorjoa/pun-api:cc83b942745d09bc83e485946c3f5b688fcfe5d0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
