apiVersion: apps/v1
kind: Deployment
metadata:
  name: pun-api
  namespace: pun-namespace
spec:
  selector:
    matchLabels:
      app: pun-api
  replicas: 3
  template:
    metadata:
      labels:
        app: pun-api
    spec:
      containers:
      - name: pun-api
        image: ghcr.io/aorjoa/pun-api:9408b6c197182124d2211cea0336cee1846a0f63
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
