apiVersion: apps/v1
kind: Deployment
metadata:
  name: pun-api
  namespace: pun-namespace
spec:
  selector:
    matchLabels:
      app: pun-api
  replicas: 3
  template:
    metadata:
      labels:
        app: pun-api
    spec:
      containers:
      - name: pun-api
        image: ghcr.io/aorjoa/pun-api:d343ab86e7c78c79ba97a8f56e77286b21a04040
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
