apiVersion: v1
kind: Service
metadata:
  name: pun-api
  namespace: pun-namespace
spec:
  ports:
  - port: 8001
    nodePort: 30000
    protocol: TCP
    targetPort: 8080
  selector:
    app: pun-api
  type: NodePort
